name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    steps:
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiKey: ${{ secrets.CF_API_KEY }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
